### ISSUE TITLE
IP Address Blocked

### ISSUE THREAD

**Issue by mashegoindustries** [victorratts13/sport-score#2]
Hi,

Package is working very well so far.

My only problem is
My IP address got blocked by sofa score for scrapping data from their API using the package(sport-score)

Is there a way to avoid being blocked by Sofascore?

**Comment by mashegoindustries** [comment]
Is there any work around you could advise me to try?

Thank you in advance

**Comment by victorratts13** [comment]
this is strange, I believe it should be the number of requests / minute you are doing.

**Comment by mashegoindustries** [comment]
Looks like too many request results in IP address temporarily getting blocked.
Just imagine my server IP address getting blocked, this means my frontend will stop working.

I will move the the code to frontend layer.
