### ISSUE TITLE
Não consigo puxar via Bet365

### ISSUE THREAD

**Issue by kaiquebarreto** [victorratts13/sport-score#3]
Não consigo puxar via Bet365! Pode me ajudar ?
Queria conseguir buscar apenas o link do jogo!

**Comment by victorratts13** [comment]
Boa noite.
Bem, pra fazer isso, você pode usar minha outra biblioteca [radar-sport-api](https://github.com/victorratts13/radar-sport-api) ela é ainda mais completa. Porem vc precisa formatar o link atraves das ``ids de eventos`` que são disponibilizadas atraves dela.

**Comment by kaiquebarreto** [comment]
Opa Boa noite, primeiramente obrigado por responder, teria algum exemplo ?
